add verible-verilog-ls style file

diff --git a/test/verilator/Makefile b/test/verilator/Makefile
--- a/test/verilator/Makefile
+++ b/test/verilator/Makefile
@@ -1,27 +1,34 @@
-default:
-	echo "verilator generating"
-	verilator \
-	-sv +1800-2012ext+<ext> \
-	-y ../../rtl/utils -y ../../rtl/common -y ../.. \
-	--cc tb.sv --exe tb.cpp --top-module tb \
-	-Mdir build --x-assign unique --x-initial unique --trace
+top = tb
+seed = 123
 
-	if [ $$? -ne 0 ]; then \
-		echo "verilator generate failed"; \
+default:
+	@echo "**********verilator generating**********"
+	@verilator \
+	--cc tb.sv --exe tb.cpp --top-module $(top) \
+	-y ../../rtl/utils -y ../../rtl/common -y ../..  \
+	-Mdir build --x-assign unique --x-initial unique --trace \
+	-j --assert --timing \
+	-Wno-WIDTH -Wno-PINMISSING -Wno-TIMESCALEMOD
+
+	@if [ $$? -ne 0 ]; then \
+		echo "**********verilator generate failed**********"; \
 		exit 1; \
 	else \
-		echo "verilator generate successfully"; \
+		echo "**********verilator generate successfully**********"; \
 	fi
 
-	echo "make building"
-	make -C build -f Vtb.mk
+	@echo "**********make building**********"
+	@make -C build -f Vtb.mk
 
-	if [ $$? -ne 0 ]; then \
-		echo "make build failed"; \
+	@if [ $$? -ne 0 ]; then \
+		echo "**********make build failed**********"; \
 		exit 1; \
 	else \
-		echo "make build successfully"; \
+		echo "**********make build successfully**********"; \
 	fi
 
 run:
-	./build/Vtb +verilator+seed+$(seed) +verilator+rand+reset+2
+	@./build/Vtb +verilator+seed+$(seed) +verilator+rand+reset+2
+
+wave:
+	gtkwave wave.vcd
